name: quadratic_solver
description: Лабораторная работа 5 — Хранение данных
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI иконки
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  
  # Для хранения данных (лабораторная 5)
  sqflite: ^2.0.0+4
  path: ^1.8.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true